name: npm-publish
on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - if: github.event.pull_request.head.repo.full_name != github.repository
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPMTOKEN }}
